"use client";

import { AlertTriangle, CheckCircle, XCircle, Repeat, Clock } from "lucide-react";
import { cn } from "@/lib/utils";

interface Props {
  stopReason: string | null;
  stopRound: number | null;
  className?: string;
}

const REASON_META: Record<string, { label: string; icon: typeof AlertTriangle; tone: string }> = {
  VERIFIER_PASS: {
    label: "All tests passed — verifier approved",
    icon: CheckCircle,
    tone: "border-emerald-400 text-emerald-600",
  },
  MAX_ROUNDS: {
    label: "Reached maximum verifier rounds",
    icon: Repeat,
    tone: "border-amber-400 text-amber-600",
  },
  NO_PATCHES: {
    label: "No patches were generated by workers",
    icon: AlertTriangle,
    tone: "border-amber-400 text-amber-600",
  },
  PATCH_APPLY_FAILED: {
    label: "Could not apply patches to source tree",
    icon: XCircle,
    tone: "border-rose-400 text-rose-600",
  },
  NO_NEXT_ACTIONS: {
    label: "Verifier could not suggest next actions",
    icon: AlertTriangle,
    tone: "border-amber-400 text-amber-600",
  },
  REPEATED_TEST_FAILURE: {
    label: "Same tests keep failing across rounds",
    icon: Repeat,
    tone: "border-rose-400 text-rose-600",
  },
  TOKEN_BUDGET: {
    label: "Token budget exhausted",
    icon: Clock,
    tone: "border-rose-400 text-rose-600",
  },
  WORKER_SCHEMA_FAILURES: {
    label: "Worker output failed schema validation repeatedly",
    icon: XCircle,
    tone: "border-rose-400 text-rose-600",
  },
  NORMAL: {
    label: "Completed normally",
    icon: CheckCircle,
    tone: "border-emerald-400 text-emerald-600",
  },
};

export function StopReasonBanner({ stopReason, stopRound, className }: Props) {
  if (!stopReason) return null;

  const meta = REASON_META[stopReason] ?? {
    label: stopReason,
    icon: AlertTriangle,
    tone: "border-muted text-muted-foreground",
  };
  const Icon = meta.icon;

  return (
    <div
      className={cn(
        "flex items-center gap-3 rounded-md border-2 bg-card px-4 py-3 text-sm",
        meta.tone,
        className,
      )}
      data-testid="stop-reason-banner"
    >
      <Icon className="h-5 w-5 shrink-0" />
      <div>
        <p className="font-semibold">{meta.label}</p>
        {stopRound != null ? (
          <p className="text-xs text-muted-foreground">Stopped at round {stopRound}</p>
        ) : null}
      </div>
    </div>
  );
}
